Enable Alarm
rackspace-infrastructure-automation/aws-terraform-ec2_asg pull request #63
Opened 2020-12-09 14:06 UTC by dunnill

##### Corresponding Issue(s):
 - PRs should have a corresponding issue. If no issue exists, provide details in the **Reason for Change(s)** section

##### Summary of change(s):
Change name to remove `}` and enabled metrics required for alarm to gather data.  Currently alarms are in "Insufficient Data" as metrics are not enabled.

##### Reason for Change(s):

- If a bug, describe error scenario, including expected behavior and actual behavior.
CW Alarm for Terminating Instances shows as Insufficient Data due to Metrics it uses not being enabled.  This will enable them so that the alarm can alert when a certain number of instances have terminated within 6h.

- If an enhancement, describe the use case and the perceived benefit(s).

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:
No - added suppression variable to enforce legacy mode where alarm does not work / no changes.  By default this is enabled.

##### Does this update/change involve issues with other external modules? If so, please describe the scenario.

##### If input variables or output variables have changed or has been added, have you updated the README?
Yes

##### Do examples need to be updated based on changes?
Should not be needed as it is fixing a bug in current functionality.

##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

2020-12-10 01:09 UTC, gdelvalle requested changes
The `module/.gitkeep` doesn't need to be there, I think the failure was resolved  by a subsequent commit to this.  I verified this on a test branch.  The logic flow on these tests are kind of wonky  so  it is worth thinking about on our end how we can more clearly surface the true error

See my other inline comments that we can discuss.

2020-12-10 01:09 UTC, gdelvalle commented on README.md
> +| enable\_all\_asg\_metrics | Should all ASG metrics be collected? If yes and not `suppress_all_asg_metrics` then all metrics are collected.  Otherwise collects Terminating metrics only, required for
My feeling is I don't like this all or nothing approach to these metrics, even if there is no cost associated.  I'd  would prefer to see something  we take list of metrics we want enabled. we can merge the that list with the `["GroupTerminatingInstances"]` list.  Then just enable whatever metrics are in our merged list.  Just as we do in a couple other places, we can enumerate the acceptable metrics or we point the user to the documentation for allowed metrics.

2020-12-10 01:09 UTC, gdelvalle commented on README.md
> +| suppress\_all\_asg\_metrics | Boolean parameter controlling if ASG group level metrics should be suppressed.  This is to ensure compatibility with previous deployments and if enabled overrides `ena
would this change cause  replacement of the ASG?  If not, I don't think its worth it to add this backward compatibility.  If so, I'll want to think about this a bit more.

2020-12-10 01:09 UTC, gdelvalle commented on main.tf
> +  asg_metrics       = var.enable_all_asg_metrics ? local.metrics_permitted : ["GroupTerminatingInstances"]
As I stated earlier, I'd just like to see a merged list if possible

2020-12-10 08:59 UTC, dunnill commented on README.md
> +| suppress\_all\_asg\_metrics | Boolean parameter controlling if ASG group level metrics should be suppressed.  This is to ensure compatibility with previous deployments and if enabled overrides `ena
I believe you are correct that this change will simply add enabled_metrics i.e. no churn.  I was 50/50 on it but was being cautious.

2020-12-10 09:01 UTC, dunnill commented on README.md
> +| enable\_all\_asg\_metrics | Should all ASG metrics be collected? If yes and not `suppress_all_asg_metrics` then all metrics are collected.  Otherwise collects Terminating metrics only, required for
Aye - I was thinking about this but wanted to avoid the risk of someone using an invalid option.  I'll re-draft with folks passing in these values instead. Thanks

2020-12-10 16:58 UTC, gdelvalle approved these changes
I think this looks good now

2020-12-11 16:12 UTC, stevengorrell approved these changes

2020-12-11 16:13 UTC, merged