Added changes for using Target Tracking Policy
rackspace-infrastructure-automation/aws-terraform-ec2_asg pull request #65
Opened 2021-01-12 17:21 UTC by dheeraj251

##### Corresponding Issue(s):
 - PRs should have a corresponding issue. If no issue exists, provide details in the **Reason for Change(s)** section

##### Summary of change(s):

Added code to configure Auto Scaling Group with Target Tracking Policy

##### Reason for Change(s):

-  The current Auto scaling module is configure with Simple Scaling Policy only. However, in build team we might get the request to configure Auto Scaling Group with Target Scaling Policy
- In Target Tracking Policy there are four metrics 'ALBRequestCountPerTarget', 'ASGAverageCPUUtilization', 'ASGAverageNetworkIn', 'ASGAverageNetworkOut'
- I have added the code to configure Target Tracking Policy with any/all of these four metrics
- I have tested my changes in AWS Playground account

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:
No
##### Does this update/change involve issues with other external modules? If so, please describe the scenario.
No
##### If input variables or output variables have changed or has been added, have you updated the README?
Yes
##### Do examples need to be updated based on changes?
No
##### Note to the PR requester about Closing PR's
Please message the person that opened the issue when auto closing it on slack, as well as any other stake holders of deep interest. Only close the issue if you believe that the issue is fully resolved with this PR.

#### This PR may auto close the issue associated with it. If you feel the issue is not resolved please reopen the issue.

2021-01-14 00:12 UTC, gdelvalle reviewed
I think we might have some back and forth here before we settle on the final solution so please take my comments in that spirit.

2021-01-14 00:12 UTC, gdelvalle commented on main.tf
> +  count                     = var.tracking_policy_network_in == true && var.enable_scaling_actions == false ? var.asg_count : 0
`var.enable_scaling_actions` set to `false` when  in truth we are setting  scaling plan is misleading  in spite of your note in the variable descriptions.  If possible i'd like to see  this variable continue to define if any type of scaling policy is in place.   Perhaps  we introduce a new variable like `policy_type`  and  then use  than in an  expression to evaluate count of the resource.  maybe like  `count =  var.policy_type == "TargetTrackingScaling"  ?  var.asg_count : 0` and we do the same for the simple scaling policy ( let the default value be simple scaling option to help with backward compatibility.

2021-01-14 08:52 UTC, dheeraj251 commented on README.md
> +| cpu\_target\_value | nter the target value for 'Average CPU Utilization' metric for Target Tracking Policy. | `string` | `"50"` | no |
I have corrected it

2021-01-14 08:53 UTC, dheeraj251 commented on README.md
> +## Requirements
I generated the new README.md file with the command provided by you. However, still CircleCI is getting fail with the same error message

2021-01-14 18:44 UTC, dheeraj251 commented on main.tf
> +  count                     = var.tracking_policy_network_in == true && var.enable_scaling_actions == false ? var.asg_count : 0
I made these changes locally  count = var.policy_type == "TargetTrackingScaling" ? var.asg_count : 0. Now if user would call policy_type as TargetTrackingScaling, then Target policy will get configure with CPU Utilisation. However, in Target policy there are 3 more metrics available which are ALB,Network-in,Network-out. So I guess I would need to add one more variable and add condition like if policy_type is TargetTrackingScaling and TargetPolicyMetric is ALB, then configure ASG with TargetTrack ALB policy. What you suggest?

2021-01-14 21:47 UTC, gdelvalle commented on README.md
> +## Requirements
ill give it a try and push to your branch

2021-01-21 13:58 UTC, johnctitus requested changes
Major concern is having 4 resources with almost identical code.  Suggested some untested changes that would help condense them.  Otherwise this looks like a solid addition to the module.

2021-01-21 13:58 UTC, johnctitus commented on main.tf
> +
These all look really similar.  Maybe we could consolidate into something like this, with some slight changes to the variables to support it, suggested separately.  But this way it would eliminate near identical code, and allow for easy support of additional metric types if\when they are added.
```suggestion
resource "aws_autoscaling_policy" "ec2_scale_up_down_target_tracking" {
  count = var.policy_type == "TargetTrackingScaling" ? var.asg_count : 0

  name                      = join("-", compact(["ec2_scale_up_down_target_tracking_policy", var.name, format("%03d", count.index + 1)]))
  autoscaling_group_name    = element(aws_autoscaling_group.autoscalegrp.*.name, count.index)
  estimated_instance_warmup = var.instance_warm_up_time
  policy_type               = "TargetTrackingScaling"
  target_tracking_configuration {
    predefined_metric_specification {
      predefined_metric_type = var.policy_type
      resource_label         = var.alb_resource_label
    }
    target_value     = var.target_value
    disable_scale_in = var.disable_scale_in
  }
}

```

2021-01-21 13:58 UTC, johnctitus commented on variables.tf
> +  default     = ""
Based on other review comments, I would suggest this default be updated to null, for better support of a unified target tracking policy resource.
```suggestion
  default     = null
```

Might also be worth thinking on we could dynamically look this information up instead of requiring it explicitly.  I would think if it is being used, we would also be getting the information to create the target group associations.  Nothing to account for now, but might be a good future improvement.

2021-01-21 13:58 UTC, johnctitus commented on variables.tf
> +}
I would update this list to the exact values required, again in an effort to unify the 4 resources into a single one.
```suggestion
variable "tracking_policy_metric" {
  description = "Enter Target Tracking Policy's metric name. Allowed Values are: ASGAverageCPUUtilization, ASGAverageNetworkIn, ASGAverageNetworkOut, ALBRequestCountPerTarget"
  type        = string
  default     = "ASGAverageCPUUtilization"
}
```

2021-01-29 18:14 UTC, dheeraj251 commented on main.tf
> +
Apoligize for the late reply. Yeah that's a very good suggestion.

2021-01-29 18:17 UTC, dheeraj251 commented on variables.tf
> +  default     = ""
Wow that null is very helpful. Thanks for this suggestion. I have used this and it shortened the whole code and no need to think of using for_loop or dynamic.  I took the suggestion and used it and updated the new commit.

2021-01-29 18:17 UTC, dheeraj251 commented on variables.tf
> +}
I have updated the variables with the exact values required

2021-02-01 15:21 UTC, johnctitus approved these changes
Everything looks good with the changes.  As mentioned, the [TFDocs](https://github.com/terraform-docs/terraform-docs) tool has a bug thats causing the readme check to fail.  You should be able to use the 0.8.2 version to rerender the readme, or shout and we can add the commit and merge the changes in.

2021-02-01 15:21 UTC, johnctitus commented on README.md
> +| alb\_resource\_label | Enter the ALB and Target group in this format : app/load-balancer-name/load-balancer-id/targetgroup/target-group-name/target-group-id | `string` | `null` | no |
Looks like we have a bug in our version of tfdocs, so its incorrectly rendering this line as:

```suggestion
| alb\_resource\_label | Enter the ALB and Target group in this format : app/load-balancer-name/load-balancer-id/targetgroup/target-group-name/target-group-id | `string` | n/a | yes |
```

2021-02-01 18:47 UTC, dheeraj251 commented on README.md
> +| alb\_resource\_label | Enter the ALB and Target group in this format : app/load-balancer-name/load-balancer-id/targetgroup/target-group-name/target-group-id | `string` | `null` | no |
My terraform-docs version is v0.10.0 which is the issue. Since you have a correct working version, hence please add the commit and merge the changes. Thanks.

2021-02-02 00:20 UTC, gdelvalle approved these changes

2021-02-02 01:14 UTC, twistedgrim approved these changes

2021-02-02 17:21 UTC, merged