Draft: Adding metrics to the ASG
rackspace-infrastructure-automation/aws-terraform-ec2_asg pull request #66
Opened 2021-01-27 17:24 UTC by triwats

##### Corresponding Issue(s):

* Unable to add issues within repository

##### Summary of change(s):

* Add definition for metric parameter map to allow for ASG Cloudwatch metrics to be available in tf-v11 version of this module as it currently is with v12 and newer outside of the scope of CW alarms.

##### Reason for Change(s):

There are currently no metrics for an ASG. In order to enable metrics in the Terraform v11 version of this using this module, we need to go in and manually enable it. Each apply, this is disabled again. This makes it problematic when you're trying to monitor and view scaling.

##### Will the change trigger resource destruction or replacement? If yes, please provide justification:

No, just an alter in place.

##### Does this update/change involve issues with other external modules? If so, please describe the scenario.

Negative

##### If input variables or output variables have changed or has been added, have you updated the README?

Yes

##### Do examples need to be updated based on changes?

It might be a good idea, but if required then please advise and I can put them in there. 

I am still testing this on a forked project with our code base, but thought I would open this first to have potential discussions around this.

2021-01-27 22:18 UTC, gdelvalle commented
This is a request to backport changes similar to #63.

2021-01-27 23:06 UTC, triwats commented
Removing draft. I've formatted this too using our projects version as provided by the RS team: 

~/src/tf-raws-uat master
❯ tf --version
Terraform v0.11.14

2021-01-28 04:54 UTC, gdelvalle requested changes
- we have a duplicate metric in the readme
- Similar to #63 , could you fix the alarm name in group_terminating_instances module.  The Last  `}`  is superfluous.  It was a lingering error for a while.
```
module "group_terminating_instances" {
  source = "git@github.com:rackspace-infrastructure-automation/aws-terraform-cloudwatch_alarm//?ref=v0.0.1"
  alarm_count              = "${var.asg_count}"
  alarm_description        = "Over ${var.terminated_instances} instances terminated in last 6 hours, generating ticket to investigate."
  alarm_name               = "${var.resource_name}-GroupTerminatingInstances}"
  comparison_operator      = "GreaterThanThreshold"
  dimensions               = "${data.null_data_source.alarm_dimensions.*.outputs}"
  evaluation_periods       = 1
  metric_name              = "GroupTerminatingInstances"
  namespace                = "AWS/AutoScaling"
  notification_topic       = "${var.notification_topic}"
```
- I think  for the tests to even work, you'll need to remove the scaleFT install option.  This was done for the 0.12 branch in #62

2021-01-28 04:54 UTC, gdelvalle commented on README.md
> +| encrypt\_primary\_ebs\_volume | Encrypt root EBS Volume? t
You've got duplicate metrics  defined in the readme `encrypt\_primary\_ebs\_volume`

2021-01-28 13:24 UTC, triwats commented on README.md
> +| encrypt\_primary\_ebs\_volume | Encrypt root EBS Volume? t
Got a bit fat fingered in vim, fixed

2021-01-28 15:10 UTC, triwats commented
Hey again @gdelvalle - thanks for the initial review and valid feedback!

**1. We have a duplicate metric in the readme**

I've fixed this

**2. Similar to #63 , could you fix the alarm name in group_terminating_instances module. The Last } is superfluous. It was a lingering error for a while.**

Noted, this has now been resolved and should evaluate correctly

**3. I think for the tests to even work, you'll need to remove the scaleFT install option. This was done for the 0.12 branch in #62**

I'm not really sure how to proceed with this one as I'm not too sure what ScaleFT does, I can try to put something in but having a bit of an understanding could help, as the blocks of definition in the test around ScaleFT are seemingly larger in the v11 version of this module.

2021-01-28 16:17 UTC, gdelvalle commented
Hi @triwats,
> I'm not really sure how to proceed with this one as I'm not too sure what ScaleFT does, I can try to put something in but having a bit of an understanding could help, as the blocks of definition in the test around ScaleFT are seemingly larger in the v11 version of this module.

Sorry about being vague here.  ScaleFT was a Rackspace specific on instance agent we moved away from.  Your changes  seem good and knocking out the scaleFT stuff isn't necessary on your end - I'll get to that.  

One problem that isn't your fault,  automated tests don't  run from forks.  I'll have to copy your changes over and I'll add  in the  scaleFT removal then.

2021-01-28 23:07 UTC, triwats commented
Hey again @gdelvalle, thanks for the explanation around ScaleFT.

I've just pushed another commit which removes any references to this that I could find and makes a note in the README. This needs another review but hpefully it makes it easier for you to just copy from the fork directly and test it. 

Let me know if you would like to make any more changes!

2021-01-29 05:16 UTC, gdelvalle commented
Hi @triwats ,  thanks for you work.  Per my earlier  comment, to get automated tests to run, I've ported your changes  over to #67  and will close this PR. Please  follow  in that thread for updates and release information.  Thanks again!

2021-01-29 05:16 UTC, closed without merging

2021-01-29 23:15 UTC, gdelvalle commented
released here: https://github.com/rackspace-infrastructure-automation/aws-terraform-ec2_asg/releases/tag/v0.0.27

2021-02-01 11:27 UTC, triwats commented
Great stuff @gdelvalle - thanks for all the help with this!